### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by youriwims** [project-jste/framework#4]
Hi! I tried testing your Jste framework "English US" demo and the calculator version did not open/work at all. The other worked, but had some web design functionality issues.

Let me know how I can be of assistance!

**Comment by GeeekyBoy** [comment]
Hi @youriwims,
Thanks for your interest in my project
It seems that you have understood the purpose of the calculator in a wrong way
Briefly, this calculator is a demo for a feature like instant apps which shows how Jste can be used to build web apps that can interact with native mobile device functions like controlling the flashlight
To try this demo, you have to install Jste Manager for Android first from: https://github.com/project-jste/manager-phone/raw/master/build/android-debug.apk then open it
After opening it it will show a splash screen which will disappear after a while
After the splash screen disappearance, try to open Jste website from Google Chrome on Android and click on the calculator link which will be opened automatically through Jste Manager
The purpose of "jste://" is to make the system open this link through Jste Manager and not through the browser
![screenshot_jste_manager_20180418-211127](https://user-images.githubusercontent.com/13814178/38953363-d10c77c0-434e-11e8-96f2-e32c88dca6a9.png)
![screenshot_jste_manager_20180418-211136](https://user-images.githubusercontent.com/13814178/38953364-d1c6c0f8-434e-11e8-8e4f-6c865ead2bff.png)

If you don't want to do all of the previous steps, you can simply open the website on Chrome PC in the mobile device mode as shown in the screenshot below
![screenshot from 2018-04-18 21-06-32](https://user-images.githubusercontent.com/13814178/38953374-da4af0c8-434e-11e8-9181-9cee94405b24.png)

Anyway, If you want to contribute to project jste, you can work on one of the issues found at: https://github.com/project-jste/framework/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
